---
frontendPublicHttpProtocol: PUBLIC_PROTOCOL
environment: REFORM_ENVIRONMENT
nodeEnvironment: NODE_ENV
gitRevision: GIT_REVISION
externalHostNameUrl: EXTERNAL_HOSTNAME_URL
featureToggles:
  launchDarklyKey: LAUNCHDARKLY_KEY
  launchDarklyUser:
    key: LD_USER_KEY
app:
  useHttps: USE_HTTPS
  port: PORT
auth:
  jwt:
    secret: JWT_SECRET
services:
  pcqBackend:
    enabled: PCQ_BACKEND_ENABLED
    url: PCQ_BACKEND_URL
tokenKeys:
  probate: PROBATE_TOKEN_KEY
  cmc: CMC_TOKEN_KEY
  divorce: DIVORCE_TOKEN_KEY
  new_divorce_law: NEW_DIVORCE_LAW_TOKEN_KEY
  sscs: SSCS_TOKEN_KEY
  iac: IAC_TOKEN_KEY
  adoption: ADOPTION_TOKEN_KEY
  et: ET_TOKEN_KEY
  online_plea: ONLINE_PLEA_TOKEN_KEY
  specialtribunals_cic: SPECIALTRIBUNALS_CIC_TOKEN_KEY
  jurordigital: JURORDIGITAL_TOKEN_KEY
  prl_ca: 'PRL_CA_TOKEN_KEY'
  civil-citizen-ui: 'CIVIL_CITIZEN_UI_TOKEN_KEY'
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  password: REDIS_PASSWORD
  useTLS: REDIS_USE_TLS
  enabled: USE_REDIS
  secret: REDIS_SECRET
hostname: FRONTEND_HOSTNAME
enableTracking: ENABLE_TRACKING
loggingEnabled: LOGGING_ENABLED
links:
  survey: SURVEY
utils:
  api:
    retries: RETRIES_NUMBER
    retryDelay: RETRY_DELAY
appInsights:
  connectionString: app-insights-connection-string
testUrl: TEST_URL
